import Head from 'next/head';
import { PropsWithChildren } from 'react';
import Navbar from './Navbar';

type LayoutProps = PropsWithChildren<{
  title: string;
}>;

const Layout = ({ title, children }: LayoutProps) => {
  return (
    <div className="container max-w-6xl py-8 mx-auto">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </div>
  );
};

export default Layout;
